package build;

import javax.swing.*;
import java.util.*;
import java.io.*;

/**
 * Unreadable class mostly generated by NetBeans
 * @author group #10 UM DKE2019
 */
public class Home extends javax.swing.JFrame {
    public void goToPhase2() {
        jPanel1.setVisible(false);
        
        int n1 = Integer.parseInt(jTextField2.getText());
        double c1 = Double.parseDouble(jTextField1.getText());
        int n2 = Integer.parseInt(jTextField4.getText());
        double c2 = Double.parseDouble(jTextField3.getText());
        int n3 = Integer.parseInt(jTextField6.getText());
        double c3 = Double.parseDouble(jTextField5.getText());
        
        boolean flag1 = jRadioButton5.isSelected();
        boolean flag2 = jRadioButton4.isSelected();
        boolean flag3 = jRadioButton6.isSelected();
        
        double res = 0;
        if (flag2 && flag1 && flag3)
            res = simulateQuickCuboidCosts(n1, c1, n2, c2, n3, c3);
        else if (flag2 && flag1)
            res = simulateLongCuboidCosts(n1, c1, n2, c2, n3, c3);
        else if (flag2 && flag3) 
            res = simulateQuickCuboidGaps(n1, c1, n2, c2, n3, c3);
        else if (flag2)
            res = simulateLongCuboidGaps(n1, c1, n2, c2, n3, c3);
        else if (flag1 && flag3)
            res = simulateQuickPentominoCosts(n1, c1, n2, c2, n3, c3);
        else if (flag1)
            res = simulateLongPentominoCosts(n1, c1, n2, c2, n3, c3);
        else if (flag3)
            res = simulateQuickPentominoGaps(n1, c1, n2, c2, n3, c3);
        else 
            res = simulateLongPentominoGaps(n1, c1, n2, c2, n3, c3);
        
        setVisible(false);
        String filename = "animation for best answer: " + res;
        JFrame frame = new JFrame(filename);
        frame.setSize(1000, 800);
        MoleculeSampleApp.performAnimation(frame);
    }

    public double simulateQuickCuboidCosts(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-final-10.log");
        BotCuboidCost tester = new BotCuboidCost();
        
        AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
        AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
        AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
        double res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(fs.size() - 1)));
        return res;
    }

    public double simulateLongCuboidCosts(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-final-10.log");
        BotCuboidCost tester = new BotCuboidCost();
        
        double res = -1e9;
        int id = 0;
        for (int i = 0; i < fs.size(); i++) {
            AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
            AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
            AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
            double ans = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(i)));
            if (ans > res) {
                res = ans;
                id = i;
            }
        }

        AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
        AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
        AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
        res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(id)));
        return res;
    }

    public double simulateQuickPentominoCosts(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-pent-cost-final-10.log");
        BotPentominoCost tester = new BotPentominoCost();

        AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
        AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
        AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
        double res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(fs.size() - 1)));
        return res;
    }

    public double simulateLongPentominoCosts(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-pent-cost-final-10.log");
        BotPentominoCost tester = new BotPentominoCost();

        double res = -1e9;
        int id = 0;
        for (int i = 0; i < fs.size(); i++) {
            AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
            AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
            AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
            double ans = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(i)));
            if (ans > res) {
                res = ans;
                id = i;
            }
        }
        AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
        AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
        AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
        res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(id)));
        return res;
    }

    public double simulateQuickCuboidGaps(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-gaps-final-10.log");
        BotCuboidGaps tester = new BotCuboidGaps();
        
        AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
        AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
        AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
        double res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(fs.size() - 1)));
        return res;
    }

    public double simulateLongCuboidGaps(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-gaps-final-10.log");
        BotCuboidGaps tester = new BotCuboidGaps();
        
        double res = -1e9;
        int id = 0;
        for (int i = 0; i < fs.size(); i++) {
            AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
            AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
            AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
            double ans = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(i)));
            if (ans > res) {
                res = ans;
                id = i;
            }
        }
        AbstractCuboidParcel obj1 = new ParcelA(c1, n1);
        AbstractCuboidParcel obj2 = new ParcelB(c2, n2);
        AbstractCuboidParcel obj3 = new ParcelC(c3, n3);
        res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(id)));
        return res; 
    }

    public double simulateQuickPentominoGaps(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-pent-gaps-final-11.log");
        BotPentominoGaps tester = new BotPentominoGaps();
        
        AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
        AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
        AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
        double res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(fs.size() - 1)));
        return res;
    }

    public double simulateLongPentominoGaps(int n1, double c1, int n2, double c2, int n3, double c3) {
        Field.init();
        ArrayList<Vec> fs = ParseFinal.parse("logs_final/population-pent-gaps-final-11.log");
        BotPentominoGaps tester = new BotPentominoGaps();
    
        double res = -1e9;
        int id = 0;
        for (int i = 0; i < fs.size(); i++) {
            AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
            AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
            AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
            double ans = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(i)));
            if (ans > res) {
                res = ans;
                id = i;
            }
        }
        AbstractPentominoParcel obj1 = new PentominoL(c1, n1);
        AbstractPentominoParcel obj2 = new PentominoP(c2, n2);
        AbstractPentominoParcel obj3 = new PentominoT(c3, n3);
        res = tester.simulate(obj1, obj2, obj3, new Function1(fs.get(id)));
        return res;
    }

    /**
     * Creates new form Home
     */
    public Home() {
        Locale.setDefault(new Locale("en", "US"));
        RandomEngine.init();
        initComponents();
        jPanel1.setVisible(true);
        jPanel1.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 820));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 780));

        jPanel5.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel5.setMinimumSize(new java.awt.Dimension(1000, 65));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 65));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(39, 39, 39));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField1.setText("1");
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(39, 39, 39));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cost of each parcel");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 65));

        jLabel2.setBackground(new java.awt.Color(39, 39, 39));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Type 1");
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 65));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(39, 39, 39));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField2.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField2.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField2.setText("1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(39, 39, 39));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number of parcels");
        jLabel3.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel3.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 65));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel7.setMinimumSize(new java.awt.Dimension(1000, 65));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(39, 39, 39));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField3.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField3.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField3.setText("1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(39, 39, 39));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cost of each parcel");
        jLabel4.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel4.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 65));

        jLabel5.setBackground(new java.awt.Color(39, 39, 39));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type 2");
        jLabel5.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 65));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(39, 39, 39));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField4.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField4.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField4.setText("1");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(39, 39, 39));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Number of parcels");
        jLabel6.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel6.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(180, 65));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel8.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel8.setMinimumSize(new java.awt.Dimension(1000, 65));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(39, 39, 39));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField5.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField5.setText("1");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(39, 39, 39));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cost of each parcel");
        jLabel7.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel7.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(180, 65));

        jLabel8.setBackground(new java.awt.Color(39, 39, 39));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Type 3");
        jLabel8.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel8.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 65));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(39, 39, 39));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setMaximumSize(new java.awt.Dimension(150, 65));
        jTextField6.setMinimumSize(new java.awt.Dimension(150, 65));
        jTextField6.setPreferredSize(new java.awt.Dimension(150, 65));
        jTextField6.setText("1");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(39, 39, 39));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Number of parcels");
        jLabel9.setMaximumSize(new java.awt.Dimension(300, 65));
        jLabel9.setMinimumSize(new java.awt.Dimension(300, 65));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(180, 65));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(39, 39, 39));
        jPanel9.setMaximumSize(null);

        jRadioButton5.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Maximize sum of costs");
        jRadioButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton5.setPreferredSize(new java.awt.Dimension(207, 65));
        jRadioButton5.setSelected(true);
        jPanel9.add(jRadioButton5);

        jRadioButton1.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup3.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Minimize gaps");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setPreferredSize(new java.awt.Dimension(139, 65));
        jRadioButton1.setSelected(false);
        jPanel9.add(jRadioButton1);

        jPanel11.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel11.setMinimumSize(new java.awt.Dimension(1000, 65));
        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 65));

        jButton2.setBackground(new java.awt.Color(39, 39, 39));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default.png"))); // NOI18N
        jButton2.setText("Solve");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(220, 65));
        jButton2.setMinimumSize(new java.awt.Dimension(220, 65));
        jButton2.setPreferredSize(new java.awt.Dimension(220, 65));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hover.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selected.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(390, 390, 390)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(390, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel6.setMinimumSize(new java.awt.Dimension(1000, 20));
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel12.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel12.setMinimumSize(new java.awt.Dimension(1000, 20));
        jPanel12.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel13.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel13.setMinimumSize(new java.awt.Dimension(1000, 20));
        jPanel13.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel14.setMaximumSize(new java.awt.Dimension(1000, 50));
        jPanel14.setMinimumSize(new java.awt.Dimension(1000, 20));
        jPanel14.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(39, 39, 39));
        jPanel10.setToolTipText("");
        jPanel10.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel10.setMinimumSize(new java.awt.Dimension(1000, 65));

        jRadioButton4.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup4.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Cuboid");
        jRadioButton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton4.setPreferredSize(new java.awt.Dimension(129, 65));
        jRadioButton4.setSelected(true);
        jPanel10.add(jRadioButton4);

        jRadioButton3.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup4.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Pentomino");
        jRadioButton3.setToolTipText("");
        jRadioButton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton3.setMaximumSize(new java.awt.Dimension(500, 65));
        jRadioButton3.setMinimumSize(new java.awt.Dimension(323, 67));
        jRadioButton3.setPreferredSize(new java.awt.Dimension(120, 65));
        jRadioButton3.setSelected(false);
        jPanel10.add(jRadioButton3);

        jPanel17.setBackground(new java.awt.Color(39, 39, 39));
        jPanel17.setToolTipText("");
        jPanel17.setMaximumSize(new java.awt.Dimension(1000, 65));
        jPanel17.setMinimumSize(new java.awt.Dimension(1000, 65));

        jRadioButton6.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Quick search");
        jRadioButton6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton6.setPreferredSize(new java.awt.Dimension(129, 65));
        jRadioButton6.setSelected(true);
        jPanel17.add(jRadioButton6);

        jRadioButton7.setBackground(new java.awt.Color(39, 39, 39));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Full search (can take up to one hour)");
        jRadioButton7.setToolTipText("");
        jRadioButton7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton7.setMaximumSize(new java.awt.Dimension(500, 65));
        jRadioButton7.setMinimumSize(new java.awt.Dimension(323, 67));
        jRadioButton7.setPreferredSize(new java.awt.Dimension(323, 67));
        jRadioButton7.setSelected(false);
        jPanel17.add(jRadioButton7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        goToPhase2();
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}
